-- Management Adjustments Table
-- Allows manual salary adjustments (positive for bonuses, negative for deductions)
-- with mandatory remarks for audit trail

CREATE TABLE IF NOT EXISTS public.salary_management_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  upload_id INTEGER NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  remarks TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT management_adjustments_employee_upload_unique
    UNIQUE (employee_id, upload_id)
);

-- Indexes for efficient lookups
CREATE INDEX IF NOT EXISTS salary_management_adjustments_employee_idx
  ON public.salary_management_adjustments(employee_id);
CREATE INDEX IF NOT EXISTS salary_management_adjustments_upload_idx
  ON public.salary_management_adjustments(upload_id);

-- Foreign key constraints
ALTER TABLE public.salary_management_adjustments
  ADD CONSTRAINT salary_management_adjustments_employee_fkey
    FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
  ADD CONSTRAINT salary_management_adjustments_upload_fkey
    FOREIGN KEY (upload_id) REFERENCES public.attendance_imports(id) ON DELETE CASCADE;

-- Enable Row Level Security
ALTER TABLE public.salary_management_adjustments ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to manage adjustments
DROP POLICY IF EXISTS management_adjustments_authenticated_access ON public.salary_management_adjustments;
CREATE POLICY management_adjustments_authenticated_access
  ON public.salary_management_adjustments FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- Comment
COMMENT ON TABLE public.salary_management_adjustments IS 'Stores manual salary adjustments (bonuses/deductions) with mandatory remarks for audit purposes';
COMMENT ON COLUMN public.salary_management_adjustments.amount IS 'Positive for bonuses, negative for deductions';
COMMENT ON COLUMN public.salary_management_adjustments.remarks IS 'Mandatory reason/documentation for the adjustment';
